/**
 * This file is auto-generated by backend/src/main.ts during vite server startup don't edit this file for any reason
*/

import React from "react";
import { Route, Routes } from "react-router";
import loadable from "@loadable/component";

const Application0=loadable(()=>import("C:/Users/ewsgi/projects/yourdash/uk-ewsgit-dash/web/src/index.tsx"));const Application1=loadable(()=>import("C:/Users/ewsgi/projects/yourdash/uk-ewsgit-nextcloud/web/src/index.tsx"));const AppRouter=[<Route path={"uk-ewsgit-dash/*"} element={<Application0/>}/>,<Route path={"uk-ewsgit-nextcloud/*"} element={<Application1/>}/>,];export default AppRouter
